Try to reduce memory usage to fix an error I don't understand
...
WARNING: curious URL in hyperlink:
Generating page for https://thearchdruidreport.blogspot.com/2016/08/learning-from-failure-modest.html ...
Generating page for https://thearchdruidreport.blogspot.com/2016/08/retrotopia-view-from-ottawa-hills.html ...
Generating page for https://thearchdruidreport.blogspot.com/2016/09/retrotopia-only-way-forward.html ...
Generating page for https://thearchdruidreport.blogspot.com/2016/09/retrotopia-cloud-that-hides-future.html ...
Generating page for https://thearchdruidreport.blogspot.com/2016/09/a-time-for-retrovation.html ...
Generating page for https://thearchdruidreport.blogspot.com/2016/09/the-coming-of-postliberal-era.html ...
WARNING: curious URL in hyperlink: toomaskarmo.blogspot.com
Generating page for https://thearchdruidreport.blogspot.com/2016/10/the-myth-of-anthropocene.html ...
Generating page for https://thearchdruidreport.blogspot.com/2016/10/an-afternoon-in-early-autumn.html ...
Generating page for https://thearchdruidreport.blogspot.com/2016/10/the-future-hiding-in-plain-sight.html ...
Generating page for https://thearchdruidreport.blogspot.com/2016/11/the-last-gasp-of-american-dream.html ...
Generating page for https://thearchdruidreport.blogspot.com/2016/11/reflections-on-democracy-in-crisis.html ...
Generating page for https://thearchdruidreport.blogspot.com/2016/11/when-shouting-stops.html ...
Generating page for https://thearchdruidreport.blogspot.com/2016/11/the-free-trade-fallacy.html ...
Generating page for https://thearchdruidreport.blogspot.com/2016/11/the-end-of-american-century.html ...
Generating page for https://thearchdruidreport.blogspot.com/2016/12/the-fifth-side-of-triangle.html ...
Generating page for https://thearchdruidreport.blogspot.com/2016/12/why-peak-oil-movement-failed.html ...
Generating page for https://thearchdruidreport.blogspot.com/2016/12/a-season-of-consequences.html ...
Generating page for https://thearchdruidreport.blogspot.com/2016/12/a-leap-in-dark.html ...
Generating page for https://thearchdruidreport.blogspot.com/2017/01/how-not-to-write-like-archdruid.html ...
Generating page for https://thearchdruidreport.blogspot.com/2017/01/the-embarrassments-of-chronocentrism.html ...
Generating page for https://thearchdruidreport.blogspot.com/2017/01/the-hate-that-dare-not-speak-its-name.html ...
Generating page for https://thearchdruidreport.blogspot.com/2017/01/how-great-fall-can-be.html ...
Generating page for https://thearchdruidreport.blogspot.com/2017/02/perched-on-wheel-of-time.html ...
Generating page for https://thearchdruidreport.blogspot.com/2017/02/the-world-as-representation.html ...
Generating page for https://thearchdruidreport.blogspot.com/2017/02/the-world-as-will.html ...
WARNING: curious URL in hyperlink: ecoshock.org/transcripts/greer_on_collapse.pdf
Generating page for https://thearchdruidreport.blogspot.com/2017/02/a-muddle-of-mind-and-matter.html ...
Generating page for https://thearchdruidreport.blogspot.com/2017/03/the-magic-lantern-show.html ...
WARNING: curious URL in hyperlink: www.theamericanconservative.com/dreher/how-the-narrative-is-made-new-york-times/
Generating page for https://thearchdruidreport.blogspot.com/2017/03/how-should-we-then-live.html ...
Generating page for https://thearchdruidreport.blogspot.com/2017/05/a-brief-announcement.html ...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1018:11)
    at WriteWrap.afterWrite (net.js:800:14)
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1018:11)
    at WriteWrap.afterWrite (net.js:800:14)
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "./generate_pages.py", line 957, in generate_single_post
    _write_page(out, OUTPUT_DIRECTORY + ("/%04d/%02d/%s" % parse_tar_url(page_url)))
  File "./generate_pages.py", line 534, in _write_page
    util.set_file_text(path, _minify_html(str(doc)))
  File "./generate_pages.py", line 525, in _minify_html
    ], stdin=subprocess.PIPE, stdout=subprocess.PIPE)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1490, in _execute_child
    restore_signals, start_new_session, preexec_fn)
OSError: [Errno 12] Cannot allocate memory
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./generate_pages.py", line 1195, in <module>
    parallel.run_main(_main)
  File ".../thearchdruidreport-archive/parallel.py", line 75, in run_main
    _main_parallel(main)
  File ".../thearchdruidreport-archive/parallel.py", line 66, in _main_parallel
    flush=(lambda: [t.get() for t in tasks] and None))
  File "./generate_pages.py", line 1190, in _main
    _generate_everything(apply_, flush)
  File "./generate_pages.py", line 1158, in _generate_everything
    flush()
  File ".../thearchdruidreport-archive/parallel.py", line 66, in <lambda>
    flush=(lambda: [t.get() for t in tasks] and None))
  File ".../thearchdruidreport-archive/parallel.py", line 66, in <listcomp>
    flush=(lambda: [t.get() for t in tasks] and None))
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
OSError: [Errno 12] Cannot allocate memory